version: 2

workflows:
  version: 2
  test_all:
    jobs:
      - jest
      - ava

jobs:
  jest:
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run Jest
          command: yarn run test:jest

      - run:
          name: Send code coverage
          command: yarn run codecov

  ava:
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run AVA
          command: yarn run test:ava

      - run:
          name: Send code coverage
          command: yarn run codecov
